# Generated by Django 5.0.2 on 2025-01-24 21:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0008_usersettings_instantly_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpamcheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('recurring_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userinstantly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spamchecks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Spamcheck',
                'verbose_name_plural': 'User Spamchecks',
                'db_table': 'user_spamcheck',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSpamcheckCampaigns',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('instantly_campaign_id', models.CharField(max_length=255)),
                ('email_account', models.CharField(max_length=255)),
                ('emailguard_tag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userinstantly')),
                ('spamcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='spamcheck.userspamcheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spamcheck_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Spamcheck Campaign',
                'verbose_name_plural': 'User Spamcheck Campaigns',
                'db_table': 'user_spamcheck_campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
