# Generated by Django 5.0.2 on 2025-01-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_usersettings_instantly_user_id'),
        ('spamcheck', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userspamcheckcampaigns',
            table='user_spamcheck_campaigns_instantly',
        ),
        migrations.CreateModel(
            name='UserSpamcheckAccounts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userinstantly')),
                ('spamcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='spamcheck.userspamcheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spamcheck_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Spamcheck Account',
                'verbose_name_plural': 'User Spamcheck Accounts',
                'db_table': 'user_spamcheck_accounts_instantly',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userspamcheckcampaigns',
            name='account_id',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='spamcheck.userspamcheckaccounts'),
        ),
    ]
