# Generated by Django 5.0.2 on 2025-01-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0002_alter_userspamcheckcampaigns_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspamcheckcampaigns',
            name='email_account',
        ),
        migrations.AddField(
            model_name='userspamcheckaccounts',
            name='email_account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
