# Generated by Django 5.0.2 on 2025-01-24 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0003_remove_userspamcheckcampaigns_email_account_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userspamcheck',
            table='user_spamcheck_instantly',
        ),
        migrations.CreateModel(
            name='UserSpamcheckCampaignOptions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('open_tracking', models.BooleanField(default=False)),
                ('link_tracking', models.BooleanField(default=False)),
                ('text_only', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('spamcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_options', to='spamcheck.userspamcheck')),
            ],
            options={
                'verbose_name': 'User Spamcheck Campaign Option',
                'verbose_name_plural': 'User Spamcheck Campaign Options',
                'db_table': 'user_spamcheck_campaign_instantly_options',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='userspamcheck',
            name='options',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spamcheck_instance', to='spamcheck.userspamcheckcampaignoptions'),
        ),
    ]
