# Generated by Django 5.0.2 on 2025-01-24 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_usersettings_instantly_user_id'),
        ('spamcheck', '0004_alter_userspamcheck_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspamcheck',
            name='organization',
        ),
        migrations.AddField(
            model_name='userspamcheck',
            name='user_organization',
            field=models.ForeignKey(db_column='user_organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.userinstantly'),
        ),
    ]
