# Generated by Django 5.0.2 on 2025-01-25 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0007_alter_userspamcheck_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheckaccounts',
            name='email_account',
            field=models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
