# Generated by Django 5.0.2 on 2025-01-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0008_alter_userspamcheckaccounts_email_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckcampaigns',
            name='campaign_status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
