# Generated by Django 5.0.2 on 2025-01-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0009_userspamcheckcampaigns_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheck',
            name='is_domain_based',
            field=models.BooleanField(default=False),
        ),
    ]
