# Generated by Django 5.0.2 on 2025-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0011_userspamcheckreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserSpamcheckReport',
        ),
    ]
