# Generated by Django 5.0.2 on 2025-01-26 14:46

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_userprofile'),
        ('spamcheck', '0012_alter_userspamcheck_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpamcheckReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_account', models.EmailField(max_length=254)),
                ('report_link', models.URLField()),
                ('google_pro_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('outlook_pro_score', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spamcheck_reports', to='settings.userinstantly')),
                ('spamcheck_instantly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='spamcheck.userspamcheck')),
            ],
            options={
                'db_table': 'user_spamcheck_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
