# Generated by Django 5.0.2 on 2025-01-26 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_userprofile'),
        ('spamcheck', '0013_userspamcheckreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheck',
            name='conditions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userspamcheck',
            name='options',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spamcheck_instance', to='spamcheck.userspamcheckcampaignoptions'),
        ),
        migrations.AlterField(
            model_name='userspamcheck',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userspamcheck',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='userspamcheck',
            name='user_organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spamchecks', to='settings.userinstantly'),
        ),
    ]
