# Generated by Django 5.0.2 on 2025-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0014_userspamcheck_conditions_alter_userspamcheck_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheck',
            name='reports_waiting_time',
            field=models.FloatField(blank=True, default=1.0, help_text='Time in hours to wait before generating reports (e.g., 0.5 for 30min, 3 for 3h)', null=True),
        ),
    ]
