# Generated by Django 5.0.2 on 2025-01-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0015_userspamcheck_reports_waiting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheck',
            name='reports_waiting_time',
            field=models.FloatField(blank=True, default=1.0, help_text='Time in hours to wait before generating reports (0 for immediate, 0.5 for 30min, 1 for 1h, etc). Default is 1h', null=True),
        ),
    ]
