# Generated by Django 5.0.2 on 2025-02-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0012_add_is_good_to_reports'),
        ('spamcheck', '0018_alter_userspamcheck_status'),
    ]

    operations = [
    ]
