# Generated by Django 5.0.2 on 2025-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0019_merge_20250205_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspamcheckreport',
            name='is_good',
        ),
    ]
