# Generated by Django 5.0.2 on 2025-02-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0020_remove_userspamcheckreport_is_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckreport',
            name='is_good',
            field=models.BooleanField(default=False, help_text='Whether this account meets the spamcheck conditions'),
        ),
    ]
