# Generated by Django 5.0.2 on 2025-02-23 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_userbison_options_and_more'),
        ('spamcheck', '0022_userspamcheckreport_bison_workspace_uuid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSpamcheckBison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=50)),
                ('is_domain_based', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('recurring_days', models.IntegerField(blank=True, null=True)),
                ('conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('reports_waiting_time', models.FloatField(blank=True, default=1.0, help_text='Time in hours to wait before generating reports (0 for immediate, 0.5 for 30min, 1 for 1h, etc). Default is 1h', null=True)),
                ('plain_text', models.BooleanField(default=False)),
                ('subject', models.TextField(help_text='Email subject template')),
                ('body', models.TextField(help_text='Email body template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_spamchecks', to=settings.AUTH_USER_MODEL)),
                ('user_organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bison_spamchecks', to='settings.userbison')),
            ],
            options={
                'verbose_name': 'User Spamcheck Bison',
                'verbose_name_plural': 'User Spamcheck Bison',
                'db_table': 'user_spamcheck_bison',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'user_organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserSpamcheckAccountsBison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email_account', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userbison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_spamcheck_accounts', to=settings.AUTH_USER_MODEL)),
                ('bison_spamcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='spamcheck.userspamcheckbison')),
            ],
            options={
                'verbose_name': 'User Spamcheck Account Bison',
                'verbose_name_plural': 'User Spamcheck Accounts Bison',
                'db_table': 'user_spamcheck_accounts_bison',
                'ordering': ['-created_at'],
            },
        ),
    ]
