# Generated by Django 5.0.2 on 2025-02-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0023_userspamcheckbison_userspamcheckaccountsbison'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckaccountsbison',
            name='last_emailguard_tag',
            field=models.CharField(blank=True, help_text='Last used EmailGuard tag UUID for this account', max_length=255, null=True),
        ),
    ]
