# Generated by Django 5.0.2 on 2025-02-23 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0026_alter_userspamcheckbisonreport_google_pro_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheckbisonreport',
            name='google_pro_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userspamcheckbisonreport',
            name='outlook_pro_score',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
