# Generated by Django 5.0.2 on 2025-02-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0027_alter_userspamcheckbisonreport_google_pro_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckbisonreport',
            name='workspace_name',
            field=models.CharField(blank=True, help_text='Name of the workspace', max_length=255, null=True),
        ),
    ]
