# Generated by Django 5.0.2 on 2025-03-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0029_spamcheckerrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckbisonreport',
            name='bounced_count',
            field=models.IntegerField(default=0, help_text='Number of bounced emails'),
        ),
        migrations.AddField(
            model_name='userspamcheckbisonreport',
            name='unique_replied_count',
            field=models.IntegerField(default=0, help_text='Number of unique replies'),
        ),
    ]
