# Generated by Django 5.0.2 on 2025-03-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0030_userspamcheckbisonreport_bounced_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckbisonreport',
            name='emails_sent_count',
            field=models.IntegerField(default=0, help_text='Total number of emails sent'),
        ),
    ]
