# Generated by Django 5.0.2 on 2025-03-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0031_userspamcheckbisonreport_emails_sent_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheckbison',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='queued', max_length=50),
        ),
    ]
