# Generated by Django 5.0.2 on 2025-03-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0033_add_update_sending_limit_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckbison',
            name='weekdays',
            field=models.CharField(blank=True, help_text='Comma-separated list of weekdays (0=Monday, 6=Sunday) when this spamcheck should run', max_length=21, null=True),
        ),
    ]
