# Generated by Django 5.0.2 on 2025-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0034_add_weekdays_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspamcheckbison',
            name='reports_waiting_time',
            field=models.FloatField(blank=True, default=1.0, help_text='Time in hours to wait before generating reports (0 for immediate, 0.5 for 30min, 1-12 for 1-12 hours). Default is 1h', null=True),
        ),
        migrations.AlterField(
            model_name='userspamcheckbison',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_for_reports', 'Waiting For Reports'), ('generating_reports', 'Generating Reports'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='queued', max_length=50),
        ),
    ]
