# Generated by Django 5.0.2 on 2025-03-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0035_alter_userspamcheckbison_reports_waiting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspamcheckbison',
            name='account_selection_type',
            field=models.CharField(choices=[('specific', 'Specific Accounts'), ('all', 'All Accounts'), ('tag_based', 'Tag-Based Selection')], default='specific', help_text='Method to select accounts for this spamcheck', max_length=20),
        ),
        migrations.AddField(
            model_name='userspamcheckbison',
            name='campaign_copy_source_id',
            field=models.CharField(blank=True, help_text='ID of campaign to copy email content from', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userspamcheckbison',
            name='exclude_tags',
            field=models.JSONField(blank=True, help_text='Tags to exclude when selecting accounts (for tag-based selection)', null=True),
        ),
        migrations.AddField(
            model_name='userspamcheckbison',
            name='include_tags',
            field=models.JSONField(blank=True, help_text='Tags to include when selecting accounts (for tag-based selection)', null=True),
        ),
    ]
