# Generated by Django 5.0.2 on 2025-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamcheck', '0037_change_spamcheck_error_log_to_integer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spamcheckerrorlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
