# Generated by Django 5.0.2 on 2025-02-25 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0012_alter_userbison_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InboxassureReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField()),
                ('organization_id', models.UUIDField()),
                ('total_accounts', models.IntegerField(default=0)),
                ('sending_power', models.IntegerField(default=0)),
                ('google_good', models.IntegerField(default=0)),
                ('google_bad', models.IntegerField(default=0)),
                ('outlook_good', models.IntegerField(default=0)),
                ('outlook_bad', models.IntegerField(default=0)),
                ('report_datetime', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inboxassure_reports',
                'ordering': ['-report_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ProviderPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_id', models.UUIDField()),
                ('provider', models.CharField(max_length=255)),
                ('total_checked_inboxes', models.IntegerField(default=0)),
                ('good_accounts_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bad_accounts_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('google_good_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('google_bad_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('outlook_good_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('outlook_bad_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reply_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bounce_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_performance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboxassureOrganizations',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inboxassure_organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id'], name='inboxassure_id_edd9a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClientOrganizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.inboxassureorganizations')),
            ],
            options={
                'db_table': 'client_organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCampaignsBison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField(help_text='Campaign ID from Bison API')),
                ('campaign_name', models.CharField(help_text='Campaign name from Bison API', max_length=255)),
                ('connected_emails_count', models.IntegerField(default=0, help_text='Number of emails connected to this campaign')),
                ('sends_per_account', models.IntegerField(default=0, help_text='Average number of sends per account')),
                ('google_score', models.FloatField(default=0, help_text='Google deliverability score (0-100)')),
                ('outlook_score', models.FloatField(default=0, help_text='Outlook deliverability score (0-100)')),
                ('max_daily_sends', models.IntegerField(default=0, help_text='Maximum daily sends')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bison_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='settings.userbison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Campaign Bison',
                'verbose_name_plural': 'User Campaigns Bison',
                'db_table': 'user_campaigns_bison',
                'unique_together': {('bison_organization', 'campaign_id')},
            },
        ),
    ]
