# Generated by Django 5.0.2 on 2025-02-25 15:21

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCampaignsBison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField(help_text='Campaign ID from Bison API')),
                ('campaign_name', models.CharField(help_text='Campaign name from Bison API', max_length=255)),
                ('connected_emails_count', models.IntegerField(default=0, help_text='Number of emails connected to this campaign')),
                ('sends_per_account', models.IntegerField(default=0, help_text='Average number of sends per account')),
                ('google_score', models.FloatField(default=0, help_text='Google deliverability score (0-100)')),
                ('outlook_score', models.FloatField(default=0, help_text='Outlook deliverability score (0-100)')),
                ('max_daily_sends', models.IntegerField(default=0, help_text='Maximum daily sends')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bison_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='settings.userbison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Campaign Bison',
                'verbose_name_plural': 'User Campaigns Bison',
                'db_table': 'user_campaigns_bison',
                'unique_together': {('bison_organization', 'campaign_id')},
            },
        ),
    ]
