# Generated by Django 5.0.2 on 2025-02-25 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_userbisondashboardsummary'),
        ('settings', '0012_alter_userbison_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBisonProviderPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_accounts', models.IntegerField(default=0)),
                ('google_score', models.FloatField(default=0.0)),
                ('outlook_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('sending_power', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBisonSendingPower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('sending_power', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userbisondashboardsummary',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='userbisondashboardsummary',
            new_name='analytics_u_user_id_dd2c91_idx',
            old_name='user_bison__user_id_0a4b86_idx',
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='at_risk_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='bison_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userbison'),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='checked_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='inbox_emails_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='inbox_emails_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='overall_deliverability',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='protected_accounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='spam_emails_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbisondashboardsummary',
            name='spam_emails_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='userbisondashboardsummary',
            table=None,
        ),
        migrations.AddField(
            model_name='userbisonproviderperformance',
            name='bison_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userbison'),
        ),
        migrations.AddField(
            model_name='userbisonproviderperformance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_provider_performances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbisonsendingpower',
            name='bison_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.userbison'),
        ),
        migrations.AddField(
            model_name='userbisonsendingpower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_sending_powers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userbisonproviderperformance',
            index=models.Index(fields=['user', 'bison_organization', 'provider_name', '-created_at'], name='analytics_u_user_id_30044a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbisonproviderperformance',
            index=models.Index(fields=['start_date', 'end_date'], name='analytics_u_start_d_7a68b0_idx'),
        ),
        migrations.AddIndex(
            model_name='userbisonsendingpower',
            index=models.Index(fields=['user', 'bison_organization', 'report_date', '-created_at'], name='analytics_u_user_id_0c6acb_idx'),
        ),
    ]
