# Generated by Django 5.0.2 on 2025-05-04 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BisonBounces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_bison_id', models.IntegerField(blank=True, null=True)),
                ('workspace_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('lead_email', models.EmailField(max_length=254)),
                ('campaign_bison_id', models.IntegerField(blank=True, null=True)),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_bison_id', models.IntegerField(blank=True, null=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('bounce_reply', models.TextField(blank=True, null=True)),
                ('bounce_bucket', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_bounces', to=settings.AUTH_USER_MODEL)),
                ('webhook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounces', to='webhook.bisonwebhook')),
            ],
        ),
    ]
