# Generated by Django 5.0.2 on 2025-05-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_bisonbounces'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisonbounces',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bisonbounces',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
