# Generated by Django 5.0.2 on 2025-05-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_bisonbounces_domain_bisonbounces_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisonbounces',
            name='bounce_reply_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
