# Generated by Django 5.0.2 on 2025-05-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_bisonbounces_bounce_reply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bisonbounces',
            name='bounce_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
