# Generated by Django 5.0.2 on 2025-01-23 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bison_organization_id', models.CharField(max_length=255)),
                ('bison_organization_name', models.CharField(max_length=255)),
                ('bison_organization_api_key', models.CharField(max_length=255)),
                ('bison_organization_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bison_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Bison',
                'verbose_name_plural': 'User Bison',
                'db_table': 'user_bison',
            },
        ),
        migrations.CreateModel(
            name='UserInstantly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instantly_organization_id', models.CharField(max_length=255)),
                ('instantly_organization_name', models.CharField(max_length=255)),
                ('instantly_organization_token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instantly_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Instantly',
                'verbose_name_plural': 'User Instantly',
                'db_table': 'user_instantly',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instantly_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('instantly_editor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instantly_editor_password', models.CharField(blank=True, max_length=255, null=True)),
                ('bison_base_url', models.URLField(blank=True, null=True)),
                ('emailguard_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('instantly_user_token', models.CharField(blank=True, max_length=255, null=True)),
                ('instantly_status', models.BooleanField(default=False)),
                ('emailguard_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'db_table': 'user_settings',
            },
        ),
    ]
