# Generated by Django 5.0.2 on 2025-01-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_userinstantly_instantly_organization_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbison',
            name='bison_organization_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userinstantly',
            name='instantly_organization_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='emailguard_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='instantly_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
