# Generated by Django 5.0.2 on 2025-01-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_userbison_bison_organization_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbison',
            name='bison_organization_id',
        ),
    ]
