# Generated by Django 5.0.2 on 2025-01-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_remove_userbison_bison_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='instantly_user_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
