# Generated by Django 5.0.2 on 2025-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_userinstantly_instantly_organization_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstantly',
            name='last_token_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_token_refresh',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
