# Generated by Django 5.0.2 on 2025-01-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_usersettings_instantly_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='instantly_api_key',
        ),
        migrations.AddField(
            model_name='userinstantly',
            name='instantly_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
