# Generated by Django 5.0.2 on 2025-02-07 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_add_base_url_to_bison'),
        ('settings', '0010_userprofile'),
    ]

    operations = [
    ]
