# Generated by Django 5.0.2 on 2025-02-07 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_merge_0002_add_base_url_to_bison_0010_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbison',
            options={},
        ),
        migrations.AlterField(
            model_name='userbison',
            name='bison_organization_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userbison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userbison',
            unique_together={('user', 'bison_organization_name')},
        ),
    ]
