# Generated by Django 5.0.2 on 2025-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0012_alter_userbison_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='URL to receive webhook notifications for completed spamchecks', max_length=500, null=True),
        ),
    ]
