# Generated by Django 5.0.2 on 2025-02-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_passwordresettoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authprofile',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50, null=True),
        ),
    ]
